// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2130.MockBoard.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2130.MockBoard.Robot;
/**
 *
 */
public class  FeederCommand extends Command {
    
    private boolean lastValue = true;
    public FeederCommand() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.proximitySubsystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        lastValue = true;
        Robot.proximitySubsystem.runFeederWindowMotor();
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        boolean currentValue = Robot.proximitySubsystem.feederProxActive();
        if(currentValue == true && lastValue == false) {
            return true;
        }
        lastValue = currentValue;
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        Timer.delay(.1);
        Robot.proximitySubsystem.stopFeederWindowMotor();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        //Robot.proximitySubsystem.stopFeederWindowMotor();
    }
}
