// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2130.MockBoard.subsystems;
import org.usfirst.frc2130.MockBoard.RobotMap;
import org.usfirst.frc2130.MockBoard.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;
import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 *
 */
public class CannonWheelPIDSubsystem extends PIDSubsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder quadratureEncoderForPID = RobotMap.cannonWheelPIDSubsystemQuadratureEncoderForPID;
    SpeedController cannonWheelTalon = RobotMap.cannonWheelPIDSubsystemCannonWheelTalon;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Initialize your subsystem here
    public CannonWheelPIDSubsystem() {
        //super("CannonWheelPIDSubsystem", 0.0, 0.0, 0.0, 1);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("CannonWheelPIDSubsystem", 0.0, 0.0, 0.0);
        setAbsoluteTolerance(6.0);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("CannonWheelPIDSubsystem", "PIDSubsystem Controller", getPIDController());
        getPIDController().setOutputRange(-1.0, 1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
        getPIDController().setPID(0.0, 0.0, 0.0, 1);
        enable();
    }
    
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
	
        return quadratureEncoderForPID.pidGet() / 3750;
    }
    
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
	//This output is reversed because the orientation of the motor and encoder?
        cannonWheelTalon.pidWrite(-output);
    }
    public void stopShooterWheelTalon() {
        cannonWheelTalon.disable();
    }
    public double shooterWheelEncoderRate() {
        return quadratureEncoderForPID.getRate();
    }
    public void disableShooterWheelTalon() {
        cannonWheelTalon.disable();
    }
    public void runShooterWheelNoPID() {
        cannonWheelTalon.set(-.8);
    }
}
